[package]
name = "sl"
version = "0.0.0"
authors = ["Finn <finn.bcd@gmail.com>"]

description = "A scientific library"
license = "CC0-1.0"

[dependencies.sl-analysis]
path = "./sl-analysis"

[dependencies.sl-sf]
path = "./sl-sf"

[dependencies.sl-plot]
path = "./sl-plot"

