[package]
name = "lm"
version = "0.0.0"
authors = ["Finn <finn.bcd@gmail.com>"]

description = "A library of mathematical algorithms"
license = "CC0-1.0"

[dependencies.lm-analysis]
path = "./lm-analysis"

[dependencies.lm-sf]
path = "./lm-sf"

[dependencies.lm-plot]
path = "./lm-plot"

