[package]
name = "lm"
version = "0.0.0"
authors = ["Finn <finn.bcd@gmail.com>"]

description = "A library of mathematics"
license = "CC0-1.0"

[dependencies.lm-quad]
path = "./lm-quad"

[dependencies.lm-sf]
path = "./lm-sf"

